### ISSUE TITLE
SDL_egl.c:479: undefined reference to `eglGetPlatformDisplay'

### ISSUE THREAD

**Issue by KatyushaScarlet** [carstene1ns/switch-sdl2-demo#2]
Hi, when I try to make this demo, it shows an error:

> /home/davem/projects/devkitpro/pacman-packages/switch/SDL2/src/SDL2-2.0.12/src/video/SDL_egl.c:479: undefined reference to `eglGetPlatformDisplay'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld: /home/davem/projects/devkitpro/pacman-packages/switch/SDL2/src/SDL2-2.0.12/src/video/SDL_egl.c:479: undefined reference to `eglGetPlatformDisplay'
collect2: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/libnx/switch_rules:80: /home/katyusha/switch/switch-sdl2-demo/switch-sdl2-demo.elf] Error 1
make: *** [Makefile:146: build] Error 2

I have already install the latest devkitA64 with switch-sdl2_mixer and switch-sdl2_image portlibs.
Is this a problem caused by missing some libraries?
Thanks!

**Comment by carstene1ns** [comment]
Sorry for the late reply, this has been fixed. It was indeed a missing library.
